apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-node
  labels:
    app: mtd
spec:
  replicas: 2 # Alta disponibilidad: siempre 2 "fantasmas" activos
  selector:
    matchLabels:
      app: mtd
  template:
    metadata:
      labels:
        app: mtd
    spec:
      containers:
      - name: ghost-app
        image: tu-registro.azurecr.io/ghost-node:v1 # Tu imagen Distroless
        ports:
        - containerPort: 8080
        
        # --- Seguridad: No permitir privilegios ---
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532 # Usuario default de Distroless
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true # Máximo Hardening
          
        # --- Recursos: Control de costos ---
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"

        # --- Health Checks: Conectados con app.py ---
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
