apiVersion: v1
kind: Service
metadata:
  name: mtd-app-service
spec:
  type: NodePort
  selector:
    app: mtd-app
  ports:
    - protocol: TCP
      port: 80 # the port that the client will see
      targetPort: 8080 #the port where flasj runs
      nodePort: 30080


  #type: LoadBalancer # automatic public 
